apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-metadata
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db-metadata
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db-metadata
    spec:
      containers:
      - name: db
        image: postgres:15
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-chart-config
              key: dbMetadata.user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-chart-config
              key: dbMetadata.password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-chart-config
              key: dbMetadata.db
        ports:
        - containerPort: 5432
