apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-metadata
spec:
  selector:
    app: {{ .Release.Name }}-db-metadata
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
