apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-hasura
    hasuraService: custom
  name: {{ .Release.Name }}-hasura
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-hasura
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-hasura
    spec:
      containers:
      - image: hasura/graphql-engine:latest.cli-migrations-v3.ubuntu
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://f1user:f1password@{{ .Release.Name }}-db-metadata:5432/f1db
        ## enable the console served by server
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ## enable debugging mode. It is recommended to disable this in production
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true"
        - name: HASURA_F1_DB
          value: postgres://f1user:f1password@{{ .Release.Name }}-db-f1:5432/f1db
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources: {}
