apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-chart-config
data:
  hasura:
    adminSecret: change_me
  dbF1:
    user: f1_user
    password: f1_password
  dbMetadata:
    user: metadata_user
    password: metadata_password
