apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-hasura
  name: {{ .Release.Name }}-hasura
  
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-hasura
  type: LoadBalancer
